window.GALLERY_ITEMS = [
  {
    id: "5-line-laser-01",
    title: "5线激光 01",
    type: "5线激光",
    description: "5线激光产品展示图。",
    image: "./assets/images/5-line-laser-01.png",
  },
  {
    id: "5-line-laser-02",
    title: "5线激光 02",
    type: "5线激光",
    description: "5线激光产品展示图。",
    image: "./assets/images/5-line-laser-02.png",
  },
  {
    id: "5-line-laser-03",
    title: "5线激光 03",
    type: "5线激光",
    description: "5线激光产品展示图。",
    image: "./assets/images/5-line-laser-03.png",
  },
  {
    id: "5-line-laser-04",
    title: "5线激光 04",
    type: "5线激光",
    description: "5线激光产品展示图。",
    image: "./assets/images/5-line-laser-04.png",
  },
  {
    id: "5-line-laser-05",
    title: "5线激光 05",
    type: "5线激光",
    description: "5线激光产品展示图。",
    image: "./assets/images/5-line-laser-05.png",
  },
  {
    id: "dough-mixer-01",
    title: "和面机 01",
    type: "和面机",
    description: "和面机产品展示图。",
    image: "./assets/images/dough-mixer-01.png",
  },
  {
    id: "dough-mixer-02",
    title: "和面机 02",
    type: "和面机",
    description: "和面机产品展示图。",
    image: "./assets/images/dough-mixer-02.png",
  },
  {
    id: "dough-mixer-03",
    title: "和面机 03",
    type: "和面机",
    description: "和面机产品展示图。",
    image: "./assets/images/dough-mixer-03.png",
  },
  {
    id: "dough-mixer-04",
    title: "和面机 04",
    type: "和面机",
    description: "和面机产品展示图。",
    image: "./assets/images/dough-mixer-04.png",
  },
  {
    id: "dough-mixer-05",
    title: "和面机 05",
    type: "和面机",
    description: "和面机产品展示图。",
    image: "./assets/images/dough-mixer-05.png",
  },
  {
    id: "solar-lamp-01",
    title: "太阳能灯具 01",
    type: "太阳能灯具",
    description: "太阳能灯具产品展示图。",
    image: "./assets/images/solar-lamp-01.png",
  },
  {
    id: "solar-lamp-02",
    title: "太阳能灯具 02",
    type: "太阳能灯具",
    description: "太阳能灯具产品展示图。",
    image: "./assets/images/solar-lamp-02.png",
  },
  {
    id: "solar-lamp-03",
    title: "太阳能灯具 03",
    type: "太阳能灯具",
    description: "太阳能灯具产品展示图。",
    image: "./assets/images/solar-lamp-03.png",
  },
  {
    id: "solar-lamp-04",
    title: "太阳能灯具 04",
    type: "太阳能灯具",
    description: "太阳能灯具产品展示图。",
    image: "./assets/images/solar-lamp-04.png",
  },
  {
    id: "solar-lamp-05",
    title: "太阳能灯具 05",
    type: "太阳能灯具",
    description: "太阳能灯具产品展示图。",
    image: "./assets/images/solar-lamp-05.png",
  },
  {
    id: "air-pump-01",
    title: "打气泵 01",
    type: "打气泵",
    description: "打气泵产品展示图。",
    image: "./assets/images/air-pump-01.png",
  },
  {
    id: "air-pump-02",
    title: "打气泵 02",
    type: "打气泵",
    description: "打气泵产品展示图。",
    image: "./assets/images/air-pump-02.png",
  },
  {
    id: "air-pump-03",
    title: "打气泵 03",
    type: "打气泵",
    description: "打气泵产品展示图。",
    image: "./assets/images/air-pump-03.png",
  },
  {
    id: "air-pump-04",
    title: "打气泵 04",
    type: "打气泵",
    description: "打气泵产品展示图。",
    image: "./assets/images/air-pump-04.png",
  },
  {
    id: "air-pump-05",
    title: "打气泵 05",
    type: "打气泵",
    description: "打气泵产品展示图。",
    image: "./assets/images/air-pump-05.png",
  },
  {
    id: "food-warmer-01",
    title: "暖食垫 01",
    type: "暖食垫",
    description: "暖食垫产品展示图。",
    image: "./assets/images/food-warmer-01.png",
  },
  {
    id: "food-warmer-02",
    title: "暖食垫 02",
    type: "暖食垫",
    description: "暖食垫产品展示图。",
    image: "./assets/images/food-warmer-02.png",
  },
  {
    id: "food-warmer-03",
    title: "暖食垫 03",
    type: "暖食垫",
    description: "暖食垫产品展示图。",
    image: "./assets/images/food-warmer-03.png",
  },
  {
    id: "food-warmer-04",
    title: "暖食垫 04",
    type: "暖食垫",
    description: "暖食垫产品展示图。",
    image: "./assets/images/food-warmer-04.png",
  },
  {
    id: "food-warmer-05",
    title: "暖食垫 05",
    type: "暖食垫",
    description: "暖食垫产品展示图。",
    image: "./assets/images/food-warmer-05.png",
  },
  {
    id: "air-fryer-01",
    title: "炸锅 01",
    type: "炸锅",
    description: "炸锅产品展示图。",
    image: "./assets/images/air-fryer-01.png",
  },
  {
    id: "air-fryer-02",
    title: "炸锅 02",
    type: "炸锅",
    description: "炸锅产品展示图。",
    image: "./assets/images/air-fryer-02.png",
  },
  {
    id: "air-fryer-03",
    title: "炸锅 03",
    type: "炸锅",
    description: "炸锅产品展示图。",
    image: "./assets/images/air-fryer-03.png",
  },
  {
    id: "air-fryer-04",
    title: "炸锅 04",
    type: "炸锅",
    description: "炸锅产品展示图。",
    image: "./assets/images/air-fryer-04.png",
  },
  {
    id: "air-fryer-05",
    title: "炸锅 05",
    type: "炸锅",
    description: "炸锅产品展示图。",
    image: "./assets/images/air-fryer-05.png",
  },
];
